platform :ios, '8.0'

target 'CCChainKit_Example' do
    use_frameworks!
#  pod 'CCChainKit', :path => '../'

    pod 'MBProgressHUD', '~> 1.0.0'

  target 'CCChainKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
