platform :ios, '8.0'

target 'CCChainKit_Example' do
    use_frameworks!
#  pod 'CCChainKit', :path => '../'

    pod 'MBProgressHUD', '~> 1.0.0'
    
    pod 'Realm', '~> 2.10.0'
    
    pod 'MGJRouter', '~> 0.9.3'
    pod 'AFNetworking/Reachability', '~> 3.1.0'
    pod 'AFNetworking/UIKit', '~> 3.1.0'

  target 'CCChainKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
